site_name: BrainVR unity framework overview
theme: material

pages: 
  - Framework overview : 'index.md'
  - Getting started : 'getting-started.md'
  - Experiment :
    - 'Overview' : 'experiment/overview.md'
    - 'API' : 'experiment/class.md'
    - 'Flow' : 'experiment/flow.md'
    - 'New experiemnt' : 'experiment/new-experiment.md'    
  - Controller objects :
    - 'Overview' : 'objects/overview.md' 
    - 'Arena object manager' : 'objects/arena-object-manager.md'    
    - 'Arena object' : 'objects/arena-object.md'
    - 'Goal manager' : 'objects/goal-manager.md'        
    - 'Goal controller' : 'objects/goal-controller.md'
    - 'Navigation manager' : 'objects/navigation-manager.md'
    - 'Navigation controller' : 'objects/navigation-controller.md'
    - 'Map controller' : 'objects/map-controller.md'
    - 'Beeper manager' : 'objects/beeper-manager.md'
    - 'Beeper controller' : 'objects/beeper-controller.md'
    - 'Experiment manager' : 'objects/experiment-manager.md'
    - 'Player controller' : 'objects/player-controller.md'
  - Logging : 'logging.md'
  - Troubleshooting : 'troubleshooting.md'

repo_name: 'brainvr/brainvr-unity-framework'
repo_url: 'https://github.com/brainvr/brainvr-unity-framework'

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences